using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Text.RegularExpressions;
using System.Diagnostics;

namespace TeamSupport.UnitTest.Helpers
{
    abstract class StopList
    {
        static HashSet<string> _stopList;

        static StopList()
        {
            _stopList = new HashSet<string>();
            foreach (string text in _words)
                _stopList.Add(text);
        }

        public static bool Contains(string text)
        {
            return _stopList.Contains(text);
        }

        public static void Content(int ticketID, string text)
        {
            text = CleanString(text).ToLower();
            string[] words = text.Split(_separators);

            StringBuilder builder = new StringBuilder();
            foreach (string value in words)
            {
                if ((value.Length < 2) || StopList.Contains(value))
                    continue;
                builder.Append($"{value} ");
            }
            System.Diagnostics.Debug.WriteLine($"{ticketID} {builder}");
        }

        public static void CheckedAdd(int hashCode, string value, Dictionary<int, string> unique)
        {
            if(unique.TryGetValue(value.GetHashCode(), out string found))
            {
                if (!found.Equals(value))   // check for duplicate hash codes
                    Debugger.Break();
            }
            else
                unique[value.GetHashCode()] = value;

        }

        public static Dictionary<int, string> UniqueWords(string text)
        {
            Dictionary<int, string> unique = new Dictionary<int, string>();
            text = CleanString(text).ToLower();
            string[] words = text.Split(_separators);

            foreach (string value in words)
            {
                if ((value.Length < 2) || StopList.Contains(value))
                    continue;
                CheckedAdd(value.GetHashCode(), value, unique);
            }

            return unique;
        }

        static char[] _separators = new char[] { ' ', '.', ',', '\t', '\n' };

        static int MaxActionTextLength = 5000;

        static string CleanString(string RawHtml)
        {
            // remove email addresses first (even if contains spaces)
            string text = Regex.Replace(RawHtml, @"\s+@", "@");
            Regex ItemRegex = new Regex(@"[\w\d._%+-]+@[ \w\d.-]+\.[\w]{2,3}");

            text = Regex.Replace(text, @"\p{C}", " "); // invisible control characters and unused code points. 
            text = Regex.Replace(text, @"<[^>]*>", String.Empty); //remove html tags
            text = Regex.Replace(text, "&nbsp;", " "); //remove HTML space
            text = Regex.Replace(text, @"[\d-]", String.Empty); //removes all digits [0-9]
            text = Regex.Replace(text, @"\s+", " ");   // remove whitespace

            Regex r = new Regex("(?:[^a-z0-9 ]|(?<=['\"])s)", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.Compiled);
            text = r.Replace(text, " ");

            if (text.Length > MaxActionTextLength)
                text = text.Substring(0, MaxActionTextLength);
            return text;
        }


        static string[] _words = new string[]
        {
            "software", "support", "ticket", "customer", "bb", "www", "teamsupport", "com", "url", "vml",
            "sender", "email", "action", "updated", "shape", "added", "technical", "representative",
            "twitter", "update", "information", "follow", "qa", "kind", "account", "reply", "provide", "experience", "great",
            "pending", "closed", "provide", "satisfied", "left", "right", "team", "initiated", "ensure", "experience", 
            "days", "goal", "issue", "steps", "contacting", "jane", "sarah", "kevin", "number", "create", "am", "pm",
            "version", "pod", "actual", "expected", "replicate", "top", "bottom", "na", "based", "confidential", "privileged", "assist", "tickets",
            "ts", "result", "files", "send", "inquiry", "additional", "brown", "edwin", "questions", "day", "chat", "created", "franklin",
            "user", "relevant", "screenshotsvideo", "log", "attach", "browser", "pin", "specialist", "disclosure",
            "business", "close", "transcript", "youre", "cc", "friendly", "intended", "prohibited", "message", "previous", "length",
            "mccutcheon", "regards", "nguyen", "status", "answer", "question", "request", "working", "people", "immediately", "investigate",
            "working", "today", "work", "subject", "call", "attached", "date", "regardsstuart", "sims", "zac", "williamson", "stuart",
            "ll", "lt", "gt", "ve",  "good", "greatly", "consideration", "future",
            "default", "behavior", "line", "system", "video", "screen", "screenshots", "click", "answered", "sincerely", "addressed", "proprietary",
            "time", "feature", "customers","feedback", "don", "page", "development", "andre", "gttps", "select", "arthur", "code", "appears",
            "ext", "fix", "doesn", "developers", "eric", "jonnie", "text", "part",

            // https://www.link-assistant.com/seo-stop-words.html
            "a",
            "able",
            "about",
            "above",
            "abroad",
            "according",
            "accordingly",
            "across",
            "actually",
            "adj",
            "after",
            "afterwards",
            "again",
            "against",
            "ago",
            "ahead",
            "aint",
            "all",
            "allow",
            "allows",
            "almost",
            "alone",
            "along",
            "alongside",
            "already",
            "also",
            "although",
            "always",
            "am",
            "amid",
            "amidst",
            "among",
            "amongst",
            "an",
            "and",
            "another",
            "any",
            "anybody",
            "anyhow",
            "anyone",
            "anything",
            "anyway",
            "anyways",
            "anywhere",
            "apart",
            "appear",
            "appreciate",
            "appropriate",
            "are",
            "arent",
            "around",
            "as",
            "as",
            "aside",
            "ask",
            "asking",
            "associated",
            "at",
            "available",
            "away",
            "awfully",
            "b",
            "back",
            "backward",
            "backwards",
            "be",
            "became",
            "because",
            "become",
            "becomes",
            "becoming",
            "been",
            "before",
            "beforehand",
            "begin",
            "behind",
            "being",
            "believe",
            "below",
            "beside",
            "besides",
            "best",
            "better",
            "between",
            "beyond",
            "both",
            "brief",
            "but",
            "by",
            "c",
            "came",
            "can",
            "cannot",
            "cant",
            "cant",
            "caption",
            "cause",
            "causes",
            "certain",
            "certainly",
            "changes",
            "clearly",
            "cmon",
            "co",
            "co.",
            "com",
            "come",
            "comes",
            "concerning",
            "consequently",
            "consider",
            "considering",
            "contain",
            "containing",
            "contains",
            "corresponding",
            "could",
            "couldnt",
            "course",
            "cs",
            "currently",
            "d",
            "dare",
            "darent",
            "definitely",
            "described",
            "despite",
            "did",
            "didnt",
            "different",
            "directly",
            "do",
            "does",
            "doesnt",
            "doing",
            "done",
            "dont",
            "down",
            "downwards",
            "during",
            "e",
            "each",
            "edu",
            "eg",
            "eight",
            "eighty",
            "either",
            "else",
            "elsewhere",
            "end",
            "ending",
            "enough",
            "entirely",
            "especially",
            "et",
            "etc",
            "even",
            "ever",
            "evermore",
            "every",
            "everybody",
            "everyone",
            "everything",
            "everywhere",
            "ex",
            "exactly",
            "example",
            "except",
            "f",
            "fairly",
            "far",
            "farther",
            "few",
            "fewer",
            "fifth",
            "first",
            "five",
            "followed",
            "following",
            "follows",
            "for",
            "forever",
            "former",
            "formerly",
            "forth",
            "forward",
            "found",
            "four",
            "from",
            "further",
            "furthermore",
            "g",
            "get",
            "gets",
            "getting",
            "given",
            "gives",
            "go",
            "goes",
            "going",
            "gone",
            "got",
            "gotten",
            "greetings",
            "h",
            "had",
            "hadnt",
            "half",
            "happens",
            "hardly",
            "has",
            "hasnt",
            "have",
            "havent",
            "having",
            "he",
            "hed",
            "hell",
            "hello",
            "help",
            "hence",
            "her",
            "here",
            "hereafter",
            "hereby",
            "herein",
            "heres",
            "hereupon",
            "hers",
            "herself",
            "hes",
            "hi",
            "him",
            "himself",
            "his",
            "hither",
            "hopefully",
            "how",
            "howbeit",
            "however",
            "hundred",
            "i",
            "id",
            "ie",
            "if",
            "ignored",
            "ill",
            "im",
            "immediate",
            "in",
            "inasmuch",
            "inc",
            "inc.",
            "indeed",
            "indicate",
            "indicated",
            "indicates",
            "inner",
            "inside",
            "insofar",
            "instead",
            "into",
            "inward",
            "is",
            "isnt",
            "it",
            "itd",
            "itll",
            "its",
            "its",
            "itself",
            "ive",
            "j",
            "just",
            "k",
            "keep",
            "keeps",
            "kept",
            "know",
            "known",
            "knows",
            "l",
            "last",
            "lately",
            "later",
            "latter",
            "latterly",
            "least",
            "less",
            "lest",
            "let",
            "lets",
            "like",
            "liked",
            "likely",
            "likewise",
            "little",
            "look",
            "looking",
            "looks",
            "low",
            "lower",
            "ltd",
            "m",
            "made",
            "mainly",
            "make",
            "makes",
            "many",
            "may",
            "maybe",
            "maynt",
            "me",
            "mean",
            "meantime",
            "meanwhile",
            "merely",
            "might",
            "mightnt",
            "mine",
            "minus",
            "miss",
            "more",
            "moreover",
            "most",
            "mostly",
            "mr",
            "mrs",
            "much",
            "must",
            "mustnt",
            "my",
            "myself",
            "n",
            "name",
            "namely",
            "nd",
            "near",
            "nearly",
            "necessary",
            "need",
            "neednt",
            "needs",
            "neither",
            "never",
            "neverf",
            "neverless",
            "nevertheless",
            "new",
            "next",
            "nine",
            "ninety",
            "no",
            "nobody",
            "non",
            "none",
            "nonetheless",
            "noone",
            "no-one",
            "nor",
            "normally",
            "not",
            "nothing",
            "notwithstanding",
            "novel",
            "now",
            "nowhere",
            "o",
            "obviously",
            "of",
            "off",
            "often",
            "oh",
            "ok",
            "okay",
            "old",
            "on",
            "once",
            "one",
            "ones",
            "ones",
            "only",
            "onto",
            "opposite",
            "or",
            "other",
            "others",
            "otherwise",
            "ought",
            "oughtnt",
            "our",
            "ours",
            "ourselves",
            "out",
            "outside",
            "over",
            "overall",
            "own",
            "p",
            "particular",
            "particularly",
            "past",
            "per",
            "perhaps",
            "placed",
            "please",
            "plus",
            "possible",
            "presumably",
            "probably",
            "provided",
            "provides",
            "q",
            "que",
            "quite",
            "qv",
            "r",
            "rather",
            "rd",
            "re",
            "really",
            "reasonably",
            "recent",
            "recently",
            "regarding",
            "regardless",
            "regards",
            "relatively",
            "respectively",
            "right",
            "round",
            "s",
            "said",
            "same",
            "saw",
            "say",
            "saying",
            "says",
            "second",
            "secondly",
            "see",
            "seeing",
            "seem",
            "seemed",
            "seeming",
            "seems",
            "seen",
            "self",
            "selves",
            "sensible",
            "sent",
            "serious",
            "seriously",
            "seven",
            "several",
            "shall",
            "shant",
            "she",
            "shed",
            "shell",
            "shes",
            "should",
            "shouldnt",
            "since",
            "six",
            "so",
            "some",
            "somebody",
            "someday",
            "somehow",
            "someone",
            "something",
            "sometime",
            "sometimes",
            "somewhat",
            "somewhere",
            "soon",
            "sorry",
            "specified",
            "specify",
            "specifying",
            "still",
            "sub",
            "such",
            "sup",
            "sure",
            "t",
            "take",
            "taken",
            "taking",
            "tell",
            "tends",
            "th",
            "than",
            "thank",
            "thanks",
            "thanx",
            "that",
            "thatll",
            "thats",
            "thats",
            "thatve",
            "the",
            "their",
            "theirs",
            "them",
            "themselves",
            "then",
            "thence",
            "there",
            "thereafter",
            "thereby",
            "thered",
            "therefore",
            "therein",
            "therell",
            "therere",
            "theres",
            "theres",
            "thereupon",
            "thereve",
            "these",
            "they",
            "theyd",
            "theyll",
            "theyre",
            "theyve",
            "thing",
            "things",
            "think",
            "third",
            "thirty",
            "this",
            "thorough",
            "thoroughly",
            "those",
            "though",
            "three",
            "through",
            "throughout",
            "thru",
            "thus",
            "till",
            "to",
            "together",
            "too",
            "took",
            "toward",
            "towards",
            "tried",
            "tries",
            "truly",
            "try",
            "trying",
            "ts",
            "twice",
            "two",
            "u",
            "un",
            "under",
            "underneath",
            "undoing",
            "unfortunately",
            "unless",
            "unlike",
            "unlikely",
            "until",
            "unto",
            "up",
            "upon",
            "upwards",
            "us",
            "use",
            "used",
            "useful",
            "uses",
            "using",
            "usually",
            "v",
            "value",
            "various",
            "versus",
            "very",
            "via",
            "viz",
            "vs",
            "w",
            "want",
            "wants",
            "was",
            "wasnt",
            "way",
            "we",
            "wed",
            "welcome",
            "well",
            "well",
            "went",
            "were",
            "were",
            "werent",
            "weve",
            "what",
            "whatever",
            "whatll",
            "whats",
            "whatve",
            "when",
            "whence",
            "whenever",
            "where",
            "whereafter",
            "whereas",
            "whereby",
            "wherein",
            "wheres",
            "whereupon",
            "wherever",
            "whether",
            "which",
            "whichever",
            "while",
            "whilst",
            "whither",
            "who",
            "whod",
            "whoever",
            "whole",
            "wholl",
            "whom",
            "whomever",
            "whos",
            "whose",
            "why",
            "will",
            "willing",
            "wish",
            "with",
            "within",
            "without",
            "wonder",
            "wont",
            "would",
            "wouldnt",
            "x",
            "y",
            "yes",
            "yet",
            "you",
            "youd",
            "youll",
            "your",
            "youre",
            "yours",
            "yourself",
            "yourselves",
            "youve",
            "z",
            "zer"
        };
    }
}


